Cycle execution times:  1
sp: fsp
size: 10G
device:
  - enp3s0f3
phynode:
  - ip: 10.203.1.126
  - username: admin
  - password: admin
#此处填写断开节点的信息
node:
  - name: ubuntu  #此处必须为diskless节点
    ip: 10.203.1.43
    username: horatio
    password: password
  - name: vplx2kjammy  #此处必须为diskful节点
    ip: 10.203.1.44
    username: horatio
    password: password
  - name: vplx2kjammy02  #此处必须为diskful节点
    ip: 10.203.1.45
    username: horatio
    password: password
#n1配置diskless，n2和n3配置diskfull
#n2固定做断网卡测试，n3固定做断节点测试