sp: sp2
size: 1G
device:
  - ens224
phynode:
  - ip: None
  - username: None
  - password: None
#此处填写断开节点的信息
node:
  - name: n1  #此处必须为diskless节点
    ip: 10.203.1.37
    username: root
    password: password
  - name: n2  #此处必须为diskful节点
    ip: 10.203.1.38
    username: root
    password: Feixi@123
  - name: n3  #此处必须为diskful节点
    ip: 10.203.1.39
    username: root
    password: password
#n1配置diskless，n2和n3配置diskfull
#n2固定做断网卡测试，n3固定做断节点测试