sp: fsp
size: 10G
device:
  - enp3s0f3
phynode:
  - ip: 10.203.1.126
  - username: admin
  - password: admin
#此处填写断开节点的信息
node:
  - name: ubuntu  #此处必须为diskless节点
    ip: 10.203.1.147
    username: root
    password: Feixi@171101
  - name: vplx2kjammy  #此处必须为diskful节点
    ip: 10.203.1.146
    username: root
    password: Feixi@171101
  - name: vplx2kjammy02  #此处必须为diskful节点
    ip: 10.203.1.145
    username: root
    password: Feixi@171101
#n1配置diskless，n2和n3配置diskfull
#n2固定做断网卡测试，n3固定做断节点测试